WITH source AS(
    SELECT *
    FROM {{ source('stage_data', 'stg_items') }}
),

final_datadragon_items as (
    SELECT
        item_id,
        name,
        gold_description,
        gold_base,
        gold_purchasable,
        gold_total,
        gold_sell,
        SummonersRift,
        HowlingAbyss,
        NexusBlitz,
        TeamfightTactics,
        FlatHPPoolMod,
        rFlatHPModPerLevel,
        FlatMPPoolMod,
        rFlatMPModPerLevel,
        PercentHPPoolMod,
        PercentMPPoolMod,
        FlatHPRegenMod,
        rFlatHPRegenModPerLevel,
        PercentHPRegenMod,
        FlatMPRegenMod,
        rFlatMPRegenModPerLevel,
        PercentMPRegenMod,
        FlatArmorMod,
        rFlatArmorModPerLevel,
        PercentArmorMod,
        rFlatArmorPenetrationMod,
        rFlatArmorPenetrationModPerLevel,
        rPercentArmorPenetrationMod,
        rPercentArmorPenetrationModPerLevel,
        FlatPhysicalDamageMod,
        rFlatPhysicalDamageModPerLevel,
        PercentPhysicalDamageMod,
        FlatMagicDamageMod,
        rFlatMagicDamageModPerLevel,
        PercentMagicDamageMod,
        FlatMovementSpeedMod,
        rFlatMovementSpeedModPerLevel,
        PercentMovementSpeedMod,
        rPercentMovementSpeedModPerLevel,
        FlatAttackSpeedMod,
        PercentAttackSpeedMod,
        rPercentAttackSpeedModPerLevel,
        rFlatDodgeMod,
        rFlatDodgeModPerLevel,
        PercentDodgeMod,
        FlatCritChanceMod,
        rFlatCritChanceModPerLevel,
        PercentCritChanceMod,
        FlatCritDamageMod,
        rFlatCritDamageModPerLevel,
        PercentCritDamageMod,
        FlatBlockMod,
        PercentBlockMod,
        FlatSpellBlockMod,
        rFlatSpellBlockModPerLevel,
        PercentSpellBlockMod,
        FlatEXPBonus,
        PercentEXPBonus,
        rPercentCooldownMod,
        rPercentCooldownModPerLevel,
        rFlatTimeDeadMod,
        rFlatTimeDeadModPerLevel,
        rPercentTimeDeadMod,
        rPercentTimeDeadModPerLevel,
        rFlatGoldPer10Mod,
        rFlatMagicPenetrationMod,
        rFlatMagicPenetrationModPerLevel,
        rPercentMagicPenetrationMod,
        rPercentMagicPenetrationModPerLevel,
        FlatEnergyRegenMod,
        rFlatEnergyRegenModPerLevel,
        FlatEnergyPoolMod,
        rFlatEnergyModPerLevel,
        PercentLifeStealMod,
        PercentSpellVampMod
    FROM source
)

SELECT *
FROM final_datadragon_items