
version: 2

models:
  - name: stg_champions
    columns:
      - name: champion_id
        tests:
          - not_null
          - unique
  - name: stg_items
    columns:
      - name: item_id
        tests:
          - not_null
          - unique
  - name: stg_maps
    columns:
      - name: map_id
        tests:
          - not_null
          - unique
  - name: stg_runes_reforged
    columns:
      - name: rune_id
        tests:
          - not_null
          - unique
  - name: stg_summonerspells
    columns:
      - name: summonerspell_id
        tests:
          - not_null
          - unique