
version: 2

sources:
    - name: stage_data
      description: 'League of legends database'
      schema: PUBLIC
      database: LEAGUE_OF_LEGENDSDB
      tables:
        - name: stg_match_details
        - name: stg_match_info
        - name: stg_players
        - name: stg_champions
        - name: stg_maps
        - name: stg_items
        - name: stg_runes_reforged
        - name: stg_summonerspells


models:
  - name: final_match_details
    columns:
      - name: matchId
        tests:
          - not_null
          - unique
  - name: final_match_info
    columns:
      - name: matchId
        tests:
          - not_null
          - unique
  - name: final_players
    columns:
      - name: summonerId
        tests:
          - not_null
          - unique
  - name: final_champions
    columns:
      - name: champion_id
        tests:
          - not_null
          - unique
  - name: final_items
    columns:
      - name: item_id
        tests:
          - not_null
          - unique
  - name: final_maps
    columns:
      - name: map_id
        tests:
          - not_null
          - unique
  - name: final_summonerspells
    columns:
      - name: summonerspell_id
        tests:
          - not_null
          - unique
  - name: final_runes_reforged
    columns:
      - name: rune_id
        tests:
          - not_null
          - unique