class sqlQueries:

    CREATE_PLAYERS_STAGING_TABLE_SQL_STRING = (
        """CREATE OR REPLACE TABLE STAGING_PLAYERS (json_data variant);"""
        )

    CREATE_MATCHDETAILS_STAGING_TABLE_SQL_STRING = (
        """CREATE OR REPLACE TABLE STAGING_MATCHDETAILS
        (
            matchId varchar(25),
            assists integer,
            baronKills integer,
            bountyLevel integer,
            champExperience integer,
            champLevel integer,
            championId integer,
            championName string,
            championTransform integer,
            consumablesPurchased integer,
            damageDealtToBuildings integer,
            damageDealtToObjectives integer,
            damageDealtToTurrets integer,
            damageSelfMitigated integer,
            deaths integer,
            detectorWardsPlaced integer,
            doubleKills integer,
            dragonKills integer,
            firstBloodAssist boolean,
            firstBloodKill boolean,
            firstTowerAssist boolean,
            firstTowerKill boolean,
            gameEndedInEarlySurrender boolean,
            gameEndedInSurrender boolean,
            goldEarned integer,
            goldSpent integer,
            individualPosition varchar,
            inhibitorKills integer,
            inhibitorTakedowns integer,
            inhibitorsLost integer,
            item0 integer,
            item1 integer,
            item2 integer,
            item3 integer,
            item4 integer,
            item5 integer,
            item6 integer,
            itemsPurchased integer,
            killingSprees integer,
            kills integer,
            lane varchar,
            largestCriticalStrike integer,
            largestKillingSpree integer,
            largestMultiKill integer,
            longestTimeSpentLiving integer,
            magicDamageDealt integer,
            magicDamageDealtToChampions integer,
            magicDamageTaken integer,
            neutralMinionsKilled integer,
            nexusKills integer,
            nexusLost integer,
            nexusTakedowns integer,
            objectivesStolen integer,
            objectivesStolenAssists integer,
            participantId integer,
            pentaKills integer,
            physicalDamageDealt integer,
            physicalDamageDealtToChampions integer,
            physicalDamageTaken integer,
            profileIcon integer,
            puuid varchar(200),
            quadraKills integer,
            riotIdName varchar(50),
            riotIdTagline varchar(50),
            role varchar(25),
            sightWardsBoughtInGame integer,
            spell1Casts integer,
            spell2Casts integer,
            spell3Casts integer,
            spell4Casts integer,
            summoner1Casts integer,
            summoner1Id integer,
            summoner2Casts integer,
            summoner2Id integer,
            summonerId varchar(200),
            summonerLevel integer,
            summonerName varchar(50),
            teamEarlySurrendered boolean,
            teamId integer,
            teamPosition varchar(25),
            timeCCingOthers integer,
            timePlayed integer,
            totalDamageDealt integer,
            totalDamageDealtToChampions integer,
            totalDamageShieldedOnTeammates integer,
            totalDamageTaken integer,
            totalHeal integer,
            totalHealsOnTeammates integer,
            totalMinionsKilled integer,
            totalTimeCCDealt integer,
            totalTimeSpentDead integer,
            totalUnitsHealed integer,
            tripleKills integer,
            trueDamageDealt integer,
            trueDamageDealtToChampions integer,
            trueDamageTaken integer,
            turretKills integer,
            turretTakedowns integer,
            turretsLost integer,
            unrealKills integer,
            visionScore integer,
            visionWardsBoughtInGame integer,
            wardsKilled integer,
            wardsPlaced integer,
            win boolean,
            eligibleForProgression boolean
        );"""
    )

    CREATE_MATCHINFO_STAGING_TABLE_SQL_STRING = (
        """CREATE OR REPLACE TABLE STAGING_MATCHINFO
        (
            matchId varchar,
            gameCreation integer,
            gameDuration integer,
            gameEndTimestamp integer,
            gameId varchar,
            gameMode string,
            gameName varchar,
            gameStartTimestamp integer,
            gameType varchar(25),
            gameVersion varchar,
            mapId integer,
            platformId varchar(3),
            queueId integer,
            tournamentCode varchar
        );"""
    )