
version: 2

sources:
    - name: match_stage_data
      description: 'League of legends database'
      schema: PUBLIC
      database: LEAGUE_OF_LEGENDSDB
      tables:
        - name: staging_matchdetails
        - name: staging_matchinfo
        # - name: staging_players_stage

models:
  - name: stg_match_details
    columns:
      - name: matchId
        tests:
          - not_null
          - unique
  - name: stg_match_info
    columns:
      - name: matchId
        tests:
          - not_null
          - unique
