
version: 2

sources:
    - name: league_of_legends_data
      description: 'League of legends database'
      schema: PUBLIC
      database: LEAGUE_OF_LEGENDSDB
      tables:
        - name: staging_match_details_stage
        - name: staging_match_info_stage
        # - name: staging_players_stage

models:
  - name: stg_match_details
    columns:
      - name: matchId
        tests:
          - not_null
          - unique
  - name: stg_match_info
    columns:
      - name: matchId
        tests:
          - not_null
          - unique
